version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  temp-sensor1:
    image: carlgira/mqtt-example-temp-sensor
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  mqtt-service1:
    image: carlgira/mqtt-example-mqtt-service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  mqtt-service2:
    image: carlgira/mqtt-example-mqtt-service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
