version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "localhost:1883:1883/tcp"
      - "localhost:9001:9001/tcp"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
  temp-sensor1:
    image: carlgira/mqtt-example-temp-sensor
    ports:
      - "localhost:8080:8080/tcp"
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  mqtt-service1:
    image: carlgira/mqtt-example-mqtt-service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  mqtt-service2:
    image: carlgira/mqtt-example-mqtt-service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
