version: '3'
services:
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
  temp-sensor1:
    image: gregnetifi/mqtt-example-temp-sensor
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  temp-sensor2:
    image: gregnetifi/mqtt-example-temp-sensor
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    depends_on:
      - mqtt-broker
  mqtt-service:
    image: gregnetifi/mqtt-example-mqtt-service
    environment:
      - "SPRING_PROFILES_ACTIVE=localdocker"
    ports:
      - "8080:8080"
    depends_on:
      - mqtt-broker
